### ISSUE TITLE
method <SmoothGraphics.bezierCurveTo> error

### ISSUE THREAD

**Issue by kevinchen2046** [pixijs/graphics-smooth#14]
use  method<SmoothGraphics.bezierCurveTo> get error ,
```
[.WebGL-00007230029B8E00] GL_INVALID_OPERATION: Internal error: 0x00000502: Vertex buffer is not big enough for the draw call.
index.html:1 WebGL: too many errors, no more errors will be reported to the console for this context.
```

**Comment by dev7355608** [comment]
Please share some code with me that allows me to reproduce this error.

**Comment by ivanpopelyshev** [comment]
OMG how! please demo

**Comment by dev7355608** [comment]
@ivanpopelyshev Today a non-polygon hole in a polygon shape was giving me the same error. I tracked that down to the fact that the holes use the line command of the shape instead of the one matching its type. Fixed that. But then I noticed why it failed so terribly: because `data.closeStroke` was false. Then I tried to draw non-closed polygons: those are not rendering at all. Something goes wrong in `PolyBuilder#line` if `closeStroke` is false.
```js
let p = new PIXI.Polygon([0, 0, 100, 0, 100, 100, 0, 100]);

p.closeStroke = false;

let g = app.stage.addChild(new PIXI.smooth.SmoothGraphics()
        .lineStyle(1)
        .beginFill(0xffffff)
        .drawPolygon(p)
        .endFill());
```

**Comment by ivanpopelyshev** [comment]
Oh, interesting

**Comment by dev7355608** [comment]
@ivanpopelyshev I figured out why this error happens and fixed it with a19cda74e20960ff0a0b372650b227f281257032: `joint` should be `endJoint`. The code produced a FILL joint, because it increased a NONE joint by one if `closeStroke` was false; therefore `hasTriangle` became true in the segment packer, which corrupted index buffer.

But after changing `joint` to `endJoint` there is still something wrong with the MITER joint:
![image](https://user-images.githubusercontent.com/31905376/158855657-72bb28a7-f1fb-4787-989e-db65656220db.png)
I'm not quite sure what exactly is happening here in this part of the code. If I comment it out, the line is rendered correctly.
https://github.com/pixijs/graphics-smooth/blob/a19cda74e20960ff0a0b372650b227f281257032/src/shapes/PolyBuilder.ts#L284-L297

**Comment by dev7355608** [comment]
@ivanpopelyshev I'm considering to remove this code entirely: https://github.com/pixijs/graphics-smooth/blob/994fb4ded0b495cf937f3e12be4c822c6bc341cd/src/shapes/PolyBuilder.ts#L260-L305
It seems to work fine without it, and it is flawed, but I'm not so sure exactly what it is supposed to do. Do you think it's save to delete this code?

**Comment by ivanpopelyshev** [comment]
Oh, hi! Thanks for checking up on me.

Yes, its one of things i coded in beginning that i didnt fix yet. You can remove it if you test degenerate cases like "line goes there and back"

**Comment by ivanpopelyshev** [comment]
Yes, it was there to save vertices. I agree to remove it because , whether instancing is implemented or not - it will make this "optimization" worseless soon
